version: "3.0"

services:
  app:
    image: alexesom/recruit-touk
    build: .
    depends_on:
      - postgres
    working_dir: /app
    ports:
      - "${PORT:-8000}:8000"
    volumes:
      - ./:/app
    stdin_open: true
    tty: true
    environment:
      INTERFACE: "0.0.0.0"
      PORT: ${PORT}
      PG_USER: ${PG_USER}
      PG_PASSWORD: ${PG_PASSWORD}
      PG_DB: ${PG_DB}
      PG_HOST: ${PG_HOST}
      PG_PORT: ${PG_PORT}
    entrypoint: [ "/entrypoint.sh" ]

  postgres:
    image: postgres:latest
    restart: always
    hostname: ${PG_HOST}
    ports:
      - "${PG_PORT:-5432}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}

volumes:
  postgres-data: